### ISSUE TITLE
CI: Add Concurrency Control to GitHub Actions Workflows

### ISSUE THREAD

**Issue by samadpls** [jonescompneurolab/hnn-core#877]
Our current GitHub Actions workflows lack concurrency control, leading to multiple workflows running simultaneously on outdated commits. This wastes resources and delays feedback.

**Proposed Solution**: Add the following concurrency control block to our workflows:
```yml
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
```
